# name: CI workflow

# on:
#     push:
#         branches: ["main"]
#     pull_request:
#         branches: ["main"]

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v4

#             - name: Install dependencies
#               run: npm install

#             - name: Run Lint
#               run: npm run lint
              